[package]
name = "temp"
version = "0.1.0"
edition = "2018"
publish = false

[dependencies]
cortex-m-rtic = "0.5.3"
panic-semihosting = "0.5.3"
cortex-m-semihosting = "0.3.5"
nrf51-hal = { git = "https://github.com/nrf-rs/nrf-hal.git", features = ["rt"] }
